on:
  pull_request: {}
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 346
        config: p/r2c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
